services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.guzzle_client:
      class: GuzzleHttp\Client

  app.services.line:
      class: TubeService\Service\LineService
      arguments: ["@doctrine.orm.default_entity_manager"]
