services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.services.securities:
      class: AppBundle\Service\SecuritiesService
      arguments: [@doctrine.orm.default_entity_manager,@database.mapper.factory]
