home:
  path:     /
  defaults: { _controller: App:Home:index }

#styleguide:
#  path:     /styleguide
#  defaults: { _controller: AppBundle:Home:styleguide }
#
#search:
#  path:     /search
#  defaults: { _controller: AppBundle:Search:list }
#
#securities_list:
#  path:     /securities
#  defaults: { _controller: AppBundle:Securities:list }
#
#securities_show:
#  path:     /securities/{isin}
#  defaults: { _controller: AppBundle:Securities:show }
