home:
  path:     /
  defaults: { _controller: App:Main:index }

settings:
  path:     /settings
  defaults: { _controller: App:Main:settings }

line:
  path:     /{line}
  defaults: { _controller: App:Main:line }
